#!/usr/bin/env python3
"""Generate the byte-integrity manifest for tracked runtime test fixtures."""

from __future__ import annotations

import argparse
import hashlib
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path, PurePosixPath

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
FIXTURE_ROOT = PurePosixPath("tests/fixtures")
MANIFEST_PATH = PurePosixPath("tests/fixture_hashes.sha256")
HEADER_LINES = (
    "# DipTrace MCP runtime fixture byte-integrity manifest v1",
    "# Generated by scripts/generate_fixture_hash_manifest.py; do not edit by hand.",
    "# SHA-256 proves byte integrity only, not DipTrace provenance or validation.",
)
SHA256_RE = re.compile(r"[0-9a-f]{64}")
NON_RUNTIME_NAMES = frozenset({".gitkeep"})
NON_RUNTIME_SUFFIXES = frozenset({".md"})


class FixtureManifestError(ValueError):
    """The tracked fixture set or its manifest is malformed."""


@dataclass(frozen=True, order=True)
class ManifestEntry:
    """One byte-exact runtime fixture."""

    path: PurePosixPath
    sha256: str


def _validate_fixture_path(raw_path: str) -> PurePosixPath:
    if not raw_path or "\\" in raw_path or any(ord(character) < 32 for character in raw_path):
        raise FixtureManifestError(f"unsafe fixture path: {raw_path!r}")
    path = PurePosixPath(raw_path)
    if (
        path.is_absolute()
        or path.as_posix() != raw_path
        or len(path.parts) < 3
        or path.parts[:2] != FIXTURE_ROOT.parts
        or any(part in {"", ".", ".."} for part in path.parts)
    ):
        raise FixtureManifestError(f"fixture path escapes or is not canonical: {raw_path!r}")
    return path


def _is_runtime_fixture(path: PurePosixPath) -> bool:
    """Exclude instructions and directory markers, not fixture data or schemas."""
    return path.name not in NON_RUNTIME_NAMES and path.suffix.lower() not in NON_RUNTIME_SUFFIXES


def tracked_runtime_fixture_paths(repository_root: Path) -> tuple[PurePosixPath, ...]:
    """Return canonical regular-file paths from the Git index."""
    completed = subprocess.run(
        [
            "git",
            "-C",
            str(repository_root),
            "ls-files",
            "--stage",
            "-z",
            "--",
            FIXTURE_ROOT.as_posix(),
        ],
        check=True,
        capture_output=True,
    )
    paths: list[PurePosixPath] = []
    seen: set[PurePosixPath] = set()
    for record in completed.stdout.split(b"\0"):
        if not record:
            continue
        metadata, separator, encoded_path = record.partition(b"\t")
        if not separator:
            raise FixtureManifestError("git ls-files returned a malformed record")
        fields = metadata.split()
        if len(fields) != 3:
            raise FixtureManifestError("git ls-files returned malformed metadata")
        mode, _object_id, stage = fields
        if stage != b"0":
            raise FixtureManifestError("fixture index contains an unresolved merge stage")
        if mode not in {b"100644", b"100755"}:
            raise FixtureManifestError(
                f"runtime fixtures must be regular files, not Git mode {mode.decode('ascii')}"
            )
        try:
            raw_path = encoded_path.decode("utf-8")
        except UnicodeDecodeError as exc:
            raise FixtureManifestError("fixture paths must be valid UTF-8") from exc
        path = _validate_fixture_path(raw_path)
        if not _is_runtime_fixture(path):
            continue
        if path in seen:
            raise FixtureManifestError(f"duplicate tracked fixture path: {path}")
        seen.add(path)
        paths.append(path)
    return tuple(sorted(paths))


def sha256_file(path: Path) -> str:
    """Hash the working-tree bytes without newline or encoding conversion."""
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def build_entries(repository_root: Path) -> tuple[ManifestEntry, ...]:
    entries: list[ManifestEntry] = []
    for relative_path in tracked_runtime_fixture_paths(repository_root):
        absolute_path = repository_root.joinpath(*relative_path.parts)
        if not absolute_path.is_file() or absolute_path.is_symlink():
            raise FixtureManifestError(
                f"tracked fixture is missing or not a regular file: {relative_path}"
            )
        entries.append(
            ManifestEntry(path=relative_path, sha256=sha256_file(absolute_path))
        )
    return tuple(entries)


def render_manifest(entries: tuple[ManifestEntry, ...]) -> str:
    if tuple(sorted(entries)) != entries:
        raise FixtureManifestError("fixture manifest entries must be path-sorted")
    lines = [*HEADER_LINES]
    lines.extend(f"{entry.sha256}  {entry.path.as_posix()}" for entry in entries)
    return "\n".join(lines) + "\n"


def parse_manifest(content: str) -> tuple[ManifestEntry, ...]:
    """Parse the strict line-oriented format and reject ambiguous paths."""
    if not content.endswith("\n"):
        raise FixtureManifestError("fixture manifest must end with a newline")
    lines = content.splitlines()
    if tuple(lines[: len(HEADER_LINES)]) != HEADER_LINES:
        raise FixtureManifestError("fixture manifest header is missing or changed")

    entries: list[ManifestEntry] = []
    seen: set[PurePosixPath] = set()
    for line in lines[len(HEADER_LINES) :]:
        if len(line) < 67 or line[64:66] != "  ":
            raise FixtureManifestError(f"malformed fixture manifest line: {line!r}")
        digest = line[:64]
        if SHA256_RE.fullmatch(digest) is None:
            raise FixtureManifestError(f"invalid SHA-256 digest: {digest!r}")
        path = _validate_fixture_path(line[66:])
        if path in seen:
            raise FixtureManifestError(f"duplicate fixture manifest path: {path}")
        seen.add(path)
        entries.append(ManifestEntry(path=path, sha256=digest))

    parsed = tuple(entries)
    if tuple(sorted(parsed)) != parsed:
        raise FixtureManifestError("fixture manifest entries are not path-sorted")
    return parsed


def generate_manifest(repository_root: Path) -> str:
    return render_manifest(build_entries(repository_root))


def check_manifest(repository_root: Path) -> bool:
    manifest_path = repository_root.joinpath(*MANIFEST_PATH.parts)
    actual = manifest_path.read_text(encoding="utf-8")
    parse_manifest(actual)
    return actual == generate_manifest(repository_root)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of rewriting when the committed manifest is stale",
    )
    args = parser.parse_args(argv)
    manifest_path = REPOSITORY_ROOT.joinpath(*MANIFEST_PATH.parts)

    if args.check:
        try:
            matches = check_manifest(REPOSITORY_ROOT)
        except (FixtureManifestError, OSError, subprocess.SubprocessError) as exc:
            print(f"FAIL: {exc}")
            return 1
        if not matches:
            print(f"FAIL: {MANIFEST_PATH} differs from tracked fixture bytes")
            return 1
        print(f"OK: {MANIFEST_PATH} matches tracked fixture bytes")
        return 0

    content = generate_manifest(REPOSITORY_ROOT)
    manifest_path.write_text(content, encoding="utf-8", newline="\n")
    print(f"Wrote {MANIFEST_PATH} with {len(build_entries(REPOSITORY_ROOT))} entries")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
